AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  eksctl-autodelete-lambda
  
  SAM Template for eksctl-autodelete-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  ListAllClustersFunc:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: list-all-clusters/
      Handler: eksctl-autodelete-lambda-list-all-clusters-func
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: GET

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AutodeleteAPI:
    Description: "API Gateway endpoint URL for cluster autodelete function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ListAllClustersFunc:
    Description: "First Lambda Function ARN"
    Value: !GetAtt ListAllClustersFunc.Arn
  ListAllClustersFuncRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ListAllClustersFuncRole.Arn
